### ISSUE TITLE
Ball acceleration doesn't work.

### ISSUE THREAD

**Issue by SanderE1** [drewavis/mpl_python#1]
As you said to get ball acceleration you change
```
for i in [0,1]:
        if ball_pos[i] > size[i] or ball_pos[i] == 0:
            ball_direction[i] *= -1
        ball_pos[i] += ball_direction[i]
```
to
```
for i in [0,1]:
        if ball_pos[i] > size[i] or ball_pos[i] == 0:
            ball_direction[i] *= -2
        ball_pos[i] += ball_direction[i]
```

it mostly works expect it acts like the roof doesn't exist, how would i fix this?

**Comment by drewavis** [comment]
You could try something like:

    for i in [0,1]:
        if ball_direction[i] < 10:
            ball_direction[i] *= 1.01
        if ball_pos[i] >= size[i] or ball_pos[i] <= 0:
            ball_direction[i] *= -1

So as long as we're not at our max speed (10) we keep increasing by 10%

Notice that I changed the ball_pos[i] == 0 to ball_pos[i] <= 0, because now it can "jump" over 0, and we wouldn't detect it.

**Comment by SanderE1** [comment]
Thanks!
